version: "3"
services:
  app:
    build: .
    volumes:
      - ./files:/app/files
    #ports:
     # - "9001:8000"
    container_name: freezingkas
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freezingkas.entrypoints=web"
      - "traefik.http.routers.freezingkas.rule=Host(`freezingkas.com`)"
      #- "traefik.http.middlewares.freezingkas-https-redirect.redirectscheme.scheme=websecure"
      #- "traefik.http.routers.freezingkas.middlewares=vaultwarden-https-redirect"
      - "traefik.http.routers.freezingkas-secure.entrypoints=websecure"
      - "traefik.http.routers.freezingkas-secure.rule=Host(`freezingkas.com`)"
      - "traefik.http.routers.freezingkas-secure.tls=true"
      - "traefik.http.routers.freezingkas-secure.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=web"


networks:
  web:
    external: true